export const paths = {
    welcome: '/',          // 👈 MUHIM
    role: '/role',
    login: '/login',
    registrDoc: "/register_doc",
    registerPat: "/register_pat",
    patient: '/patients',
    patientProfile: '/patients/:id',
    profile: '/profile',
    menu: '/menu',
    settings: '/settings',
    appointments: '/appointments',
    analytics: '/analytics',
    finance: '/analytics/finance',
    chats: '/chats',
    chatDetail: '/chats/:id',
    patientHome: '/home',
    patientCalendar: '/calendar',
    patientHistory: '/history',
    patientProfileSettings: '/profile_pat',
    patientAppointmentDetail: '/appointment/:id',
    patientChats: '/patient/chats',
    patientChatDetail: '/patient/chats/:id',
    doctors: '/doctors',
    booking: '/booking',
    checkupPreview: '/booking/checkup-preview'
} as const;
